name: Run Playwright Tests
'on':
  schedule:
    - cron: 10 16 * * *
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run Playwright Tests
        run: npx playwright test
