name: Run Playwright Tests

on:
  schedule:
    - cron: '40 09 * * *'  # 15:10 IST converted to 09:40 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npx playwright install

    - name: Run Playwright Tests
      run: |
        npx playwright test --reporter=html
        npx playwright show-report > summary.txt

    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-html-report
        path: playwright-report

    - name: Send Email with Test Summary
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: 'Playwright Test Results Summary'
        body: |
          <p>Playwright test results summary:</p>
          <pre>$(cat summary.txt)</pre>
        to: 'recipient@example.com'
        from: ${{ secrets.SMTP_USERNAME }}
        attachments: |
          playwright-report/*.html
