name: Run Playwright Tests

on:
  schedule:
    - cron: '13 07 * * *'  # 12:30 IST converted to 07:10 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npx playwright install

    - name: Run Playwright Tests
      run: npx playwright test --reporter=html

    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-html-report
        path: playwright-report

    - name: Generate Test Summary
      run: |
        if [ -f playwright-report/index.html ]; then
          echo "Playwright tests completed. HTML report is attached." > summary.txt
        else
          echo "Playwright tests failed or HTML report not found." > summary.txt
        fi

    - name: Send Email with Report
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        REPORT_PATH=$(find . -name 'index.html')
        echo "Sending email with HTML report and summary..."
        curl -X POST "https://api.sendgrid.com/v3/mail/send" \
          -H "Authorization: Bearer $SENDGRID_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "personalizations": [
              {
                "to": [
                  {"email": "aneripatel292@gmail.com"}
                ],
                "subject": "Playwright Test Results"
              }
            ],
            "from": {"email": "aneripatel292@gmail.com"},
            "content": [
              {
                "type": "text/html",
                "value": "<p>Playwright test results summary:</p><p><b>Summary:</b></p><p>$(cat summary.txt)</p><p><b>HTML Report:</b></p><p><a href=\"${{ github.server_url }}/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ steps.upload-report.outputs.artifact_id }}/playwright-report/index.html\">View Report</a></p>"
              }
            ],
            "attachments": [
              {
                "content": "'"$(base64 "$REPORT_PATH")"'",
                "type": "text/html",
                "filename": "playwright-report.html"
              }
            ]
          }'

