name: Run Playwright Tests

on:
  schedule:
    - cron: '30 07 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npx playwright install

    - name: Run Playwright Tests
      run: npx playwright test --reporter=html

    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-html-report
        path: playwright-report

    - name: Generate Summary
      run: |
        echo "Playwright tests completed." > summary.txt
        echo "HTML report is available as an artifact." >> summary.txt
        echo "Summary of test results:" >> summary.txt
        cat playwright-report/index.html >> summary.txt
        echo "### Test Results Summary" >> $GITHUB_STEP_SUMMARY
        cat summary.txt >> $GITHUB_STEP_SUMMARY
